{% set name = "BatAnalysis" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/BatAnalysis-{{ version }}.tar.gz
  sha256: bbd62cec6b9851ae162ab63a7845b3d4e0608a738639b501d15f264605108f17

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - setuptools >=58.0.4
    - numpy >=1.20.3
    - matplotlib-base >=3.4.2
    - astropy-base >=4.3.1
    - astroquery >=0.4.5
    - swiftbat >=0.1.2a3
    - swifttools >=2.4.8
    - scipy >=1.7.2
    - requests >=2.20
    - joblib >=1.1.0
    - dpath >=2.1.4

test:
  imports:
    - batanalysis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/parsotat/BatAnalysis
  summary: Routines for analyzing data from BAT on the Neil Gehrels Swift Observatory
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaeakle
